// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"basic-vsr-web-client/internal/biz"
	"basic-vsr-web-client/internal/conf"
	"basic-vsr-web-client/internal/data"
	"basic-vsr-web-client/internal/server"
	"basic-vsr-web-client/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	basicVSRRepo := data.NewUserRepo(dataData, logger)
	basicVSRUsecase := biz.NewBasicVSRUsecase(basicVSRRepo, logger)
	basicVSRService := service.NewBasicVSRService(basicVSRUsecase)
	grpcServer := server.NewGRPCServer(confServer, basicVSRService, logger)
	httpServer := server.NewHTTPServer(confServer, basicVSRService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
